networks:
  c1_c4:
    driver: bridge
  c2_c4:
    driver: bridge
  c3_c4:
    driver: bridge

services:
  c1:
    build: ./c1
    container_name: c1
    networks:
      - c1_c4
  c2:
    build: ./c2
    container_name: c2
    networks:
      - c2_c4
  c3:
    build: ./c3
    container_name: c3
    networks:
      - c3_c4
  c4:
    build: ./servidorC4
    container_name: servidor_c4
    networks:
      - c1_c4
      - c2_c4
      - c3_c4